### ISSUE TITLE
npm run build error

### ISSUE THREAD

**Issue by pointer** [Cambalab/fake-data-generator#78]
Hi All,
When i npm run build or prepare, i get

> fake-data-generator@0.4.2 build C:\_dev\fake-data-generator
> node node_modules/.bin/rimraf dist/ && node_modules/.bin/babel ./ --out-dir dist/ --ignore  ./node_modules,./.babelrc,./npm-debug.log --copy-files

C:\_dev\fake-data-generator\node_modules\.bin\rimraf:2
**basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list**
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
Thanks in advance

**Comment by sgobotta** [comment]
Hello @pointer . Thanks for pointing this out. Looks like a problem with `rimraf` in Windows environments. I'll get around it somehow to make the `build` script a bit more "cross-environment" since other people had the same issue.
